http:
  host: 127.0.0.1
  port: 8765

log:
  path: logs
  name: server
  level: debug
  max_age: 168
  rotation_time: 24

db:
  driver: sqlite
  url: ./db.sqlite

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0

auth:
  enable: true
  token_secret_key: secret
  token_expire_time: 86400
  ignore_paths:
    - /api/v1/login
    - /api/v1/register


