definitions:
  handler.Response:
    properties:
      code:
        type: integer
      data: {}
      message: {}
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        type: string
      phone:
        type: string
      status:
        maximum: 1
        minimum: -1
        type: integer
      updatedAt:
        type: string
      username:
        type: string
    required:
    - status
    - username
    type: object
info:
  contact: {}
paths:
  /api/users:
    post:
      parameters:
      - description: User
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/handler.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: internal error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: User Create
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
